
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";


import { UserGuard } from "app";


const Accounts = lazy(() => import("./pages/Accounts.tsx"));
const App = lazy(() => import("./pages/App.tsx"));
const Contacts = lazy(() => import("./pages/Contacts.tsx"));
const Dashboard = lazy(() => import("./pages/Dashboard.tsx"));
const FirebaseTest = lazy(() => import("./pages/FirebaseTest.tsx"));
const Pipeline = lazy(() => import("./pages/Pipeline.tsx"));
const Setup = lazy(() => import("./pages/Setup.tsx"));
const Tasks = lazy(() => import("./pages/Tasks.tsx"));
const Team = lazy(() => import("./pages/Team.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/accounts", element: <UserGuard><Accounts /></UserGuard>},
	{ path: "/", element: <App />},
	{ path: "/contacts", element: <UserGuard><Contacts /></UserGuard>},
	{ path: "/dashboard", element: <UserGuard><Dashboard /></UserGuard>},
	{ path: "/firebase-test", element: <UserGuard><FirebaseTest /></UserGuard>},
	{ path: "/firebasetest", element: <UserGuard><FirebaseTest /></UserGuard>},
	{ path: "/pipeline", element: <UserGuard><Pipeline /></UserGuard>},
	{ path: "/setup", element: <UserGuard><Setup /></UserGuard>},
	{ path: "/tasks", element: <UserGuard><Tasks /></UserGuard>},
	{ path: "/team", element: <UserGuard><Team /></UserGuard>},

];
